Fastcode/NUClear

.travis.yml
README.md

Travis's URL for the badge is set to develop which is out of date

Fix the travis badge URL

---

cmake/Modules/FindCATCH.cmake
cmake/Modules/HeaderLibrary.cmake
src/util/network/get_interfaces.cpp

Other network devices such as CAN buses show up with getinterfaces.
These didn't have IP addresses and would cause a segfault.
Also fixes the URL for Catch changing

Fix getinterfaces finding CAN buses and segfaulting

---

tests/dsl/UDPMulticastKnownPort.cpp
tests/dsl/UDPMulticastUnknownPort.cpp

I figured I would do something about the CI failures (particularly for macOS) that keep occurring. I reasoned that the failures were due to a race condition between the `known` and `unknown` tests. The counts were incremented in reactions that might have been queued, but shutdown was triggered as soon as both had a count of _at least one_.
I benchmarked how often they failed on my desktop and after. Before, in a abit over 49k runs, I had 23 failures - roughly one failure per 2138 runs. After, I ran both of them (because there are two now) 200k+ times without a single failure.
I presume something about either the macOS scheduling or something about the macOS machines doing the CI tests makes them fail more often, but without a single failure in 200k+ runs, I think it's _somewhat_ safe to …

Refactor UDP Multicast test into two non-conflicting tests

---

src/util/CallableInfo.hpp
src/util/Sequence.hpp
src/util/unpack.hpp

I was thinking about writing a reaction test API in NUClear, but then I got distracted. I figured I might as well fix these that I spotted while I was here though :shrug:

Fix some comment typos

---

src/util/FunctionFusion.hpp
src/util/TypeMap.hpp
tests/dsl/FusionInOrder.cpp

Currently when you have multiple DSL words in an `on` statement the order they execute is undefined according to the standard.
This can be confusing when you're writing an extension and expect them to execute in the order they appear.
This change changes the function fusion system to execute the functions in the order they appear rather than leaving it up to the compiler to choose.
It seems that for GCC at least the order is the inverse of the order of the arguments hence leading to this fix.

Fix DSL words so they execute in the order they appear

---

src/PowerPlant.cpp
src/PowerPlant.ipp
tests/log/Log.cpp

If a `log` happens after a call to `powerplant.shutdown()` then the call to `shutdown()` will fail and the powerplant will segfault. This PR aims to fix this

Prevent powerplant nullptr from inhibiting shutdown

---

src/PowerPlant.hpp
src/PowerPlant.ipp

This also seems to fix the timeouts that are happening in #54

Take shared pointers by value rather than rvalue as it's safer for multiple targets

---

src/PowerPlant.ipp
src/message/LogMessage.hpp
src/threading/ReactionTask.hpp
src/util/CallbackGenerator.hpp

Was going through some of my old PRs. I reckon that having a warning here is kinda dumb, and that its better to not need the warning. The comment says "persists after this" which does imply that the object could possibly have lifetime beyond the ReactionTask.

Make ReactionStatistics shared

---

src/threading/ReactionTask.hpp

When using a non-monotonic clock (e.g. system_clock) as the source for NUClear it's possible that timestamps change enough that fast emits can end up slightly out of order. The reaction task id is far more reliable as it is always monotonic.

Change the sort order for tasks to be by id rather than timestamp

---

src/Reactor.hpp
src/dsl/word/Always.hpp
src/message/ReactionStatistics.hpp
src/threading/Reaction.hpp
src/threading/ReactionIdentifiers.hpp
src/threading/ReactionTask.hpp
tests/api/ReactionStatistics.cpp

Currently, the identifiers are just stored in an `std::vector` of `std::string`s. It makes it very difficult to know what each of the different identifiers available for a reaction are.
This changes it to be a struct so you can access the fields you care about.

Store the identifiers in a struct to help know what they mean

---

src/extension/ChronoController.hpp
src/util/precise_sleep.cpp
src/util/precise_sleep.hpp

Currently, the chrono controller will often oversleep and the resulting timings can be a little off.
This refactors the controller so that it keeps track of how much it oversleeps and ensures that it spinlocks to have accurate timing.
This is a particular problem on the windows CI where the sleep accuracy is often up to 14ms off.
Extracted from #70

Refactor the chrono controller to have higher accuracy

---

src/PowerPlant.cpp
src/PowerPlant.hpp
src/dsl/word/Always.hpp
src/dsl/word/Every.hpp
src/dsl/word/Watchdog.hpp
src/dsl/word/emit/Direct.hpp
src/dsl/word/emit/Initialise.hpp
src/dsl/word/emit/Local.hpp
src/extension/IOController_Posix.hpp
src/extension/IOController_Windows.hpp
src/extension/NetworkController.hpp
src/threading/Reaction.hpp
src/threading/ReactionTask.hpp
src/threading/TaskScheduler.cpp
src/threading/TaskScheduler.hpp

Currently the Task Scheduler can only schedule reaction tasks.
It's useful for features like Initialise if generic functions can be scheduled rather than only reactions.
This PR refactors the task scheduler so it can take any generic function and schedule it as it would a reaction.

Refactor the task scheduler so it can take generic tasks

---

.readthedocs.yaml

Readthedocs is deprecating the previous method, this updates to using a config file

Add a readthedocs yaml file

---

.github/workflows/main.yaml

Updates unsupported GitHub actions that were using node 12

Update unsupported actions

---

src/util/demangle.cpp
tests/CMakeLists.txt
tests/util/demangle.cpp

Demangle returned different results on different platforms.
This makes it a bit more consistent (anonymous namespaces are still different).
Also adds a test to ensure that it works properly on different platforms.

Make the demangle function consistent across platforms and add a test

---

.github/workflows/sonarcloud.yaml

Code coverage calculations work better with debug symbols.
This swaps to using debug.
Tests may start failing due to timing constraints so those will have to be accounted for

Swap to debug build for coverage counts

---

src/Environment.hpp
src/LogLevel.hpp
src/PowerPlant.hpp
src/PowerPlant.ipp
src/Reactor.hpp
src/message/LogMessage.hpp
tests/log/Log.cpp

For many log handlers, the display level is important as only the logs you want to view should be displayed.
This display level has been typically set using the log level in each reactor and nuclear has filtered out logs below the display level from reaching the log handlers.
However, some log handlers are able to store and process logs more intelligently and make them available to access beyond their set display level.

Make NUClear logs always emit

---

src/PowerPlant.cpp
src/PowerPlant.hpp
src/dsl/operation/ChronoTask.hpp
src/dsl/word/Always.hpp
src/dsl/word/IO.hpp
src/id.hpp
src/message/ReactionStatistics.hpp
src/threading/Reaction.cpp
src/threading/Reaction.hpp
src/threading/ReactionTask.hpp
src/threading/TaskScheduler.cpp
src/threading/TaskScheduler.hpp
src/util/GroupDescriptor.hpp
src/util/ThreadPoolDescriptor.cpp
src/util/ThreadPoolDescriptor.hpp

uint64_t is larger than is necessary on a system for IDs most of the time.
On 32-bit systems, it also causes problems due to uint64_t having alignment requirements.
Swaps to using size_t for the ID which should serve the purposes of being fast and appropriately sized for the system.

Swap to using size_t as an id type

---

docs/networking.rst
src/PowerPlant.cpp
src/dsl/word/Network.hpp
src/dsl/word/UDP.hpp
src/dsl/word/emit/Network.hpp
src/dsl/word/emit/UDP.hpp
src/extension/NetworkController.hpp
src/extension/network/NUClearNetwork.cpp
src/extension/network/NUClearNetwork.hpp
src/id.hpp
src/threading/ReactionTask.hpp
src/util/serialise/Serialise.hpp
tests/dsl/UDP.cpp
tests/util/serialise/serialise.cpp

Makes the serialisation code handle trivially copyable types.
Also fixes the iterable version as it had a buffer overflow error

Fix Serialisation to properly deal with trivially copyable types

---

src/extension/IOController_Posix.hpp

It would appear that `poll()` will repeatedly return `POLLIN` provided that any call to `read()` on the `fd` will not block. This allows for the following scenario
1. New data arrives on TCP connection
2. `poll()` returns with `POLLIN` and there are `N` bytes available for reading 
3. `on<IO>` is triggered with `N > 0` number of bytes to process
4. `on<IO>` processes `N + M` bytes
5. While `on<IO>` is processing `N + M` bytes, `poll()` returns with `POLLIN` and there are `M` bytes available reading
6. `process_events` is called and sees 0 bytes available for reading (because `on<IO>` just processed the `M` newly arrived bytes)
7. `process_events` thinks EOF has been reached and flags the `fd` to be closed

Prevent spurious events from poll

---

src/threading/TaskScheduler.cpp
src/threading/TaskScheduler.hpp

Update condition for running global idle task to use total runnable task count rather then the current total idle threads to fix race condition.

Update condition for running global idle task to use total runnable task count

---

.github/workflows/gcc.yaml
src/PowerPlant.cpp
src/PowerPlant.hpp
src/Reactor.hpp
src/dsl/word/Always.hpp
src/dsl/word/Idle.hpp
src/dsl/word/MainThread.hpp
src/dsl/word/Pool.hpp
src/threading/TaskScheduler.cpp
src/threading/TaskScheduler.hpp
src/util/GeneratedCallback.hpp
src/util/ThreadPoolDescriptor.hpp
tests/dsl/Idle.cpp
tests/dsl/IdleSync.cpp
tests/dsl/MainThread.cpp
tests/dsl/Sync.cpp
tests/test_util/TestBase.hpp

Adds a new DSL word Idle that can be used to execute a reaction when the pool does not have a current task.
There are 4 main variants that this implements
```cpp
on<Idle<>>
```
Will execute when all non always threads are idle
```cpp
on<Idle<Pool<>>
```
Will execute when the default thread pool is idle
```cpp
on<Idle<MainThread>>
```
Will execute when the main thread's pool is idle
```cpp
on<Idle<SomePoolDescriptor>>
```
Will execute when that specific pool is idle

Add a DSL word that runs when a specific pool or all pools are idle

---

.github/workflows/macos.yaml
src/extension/network/NUClearNetwork.hpp
tests/dsl/emit/Delay.cpp
tests/individual/TimeTravel.cpp
tests/test_util/TimeUnit.hpp

The osx runners in GHA are so slow they can't keep up with a 1/25 event timing.
Change the event timing to be in a single file and configurable so that the macos CI runners can have a slower tolerance

Change the CI test units to be configurable using defines

---

src/extension/ChronoController.hpp

When time travelling in NEAREST mode with no chrono tasks, the code would try to dereference an empty list. Fix this to ensure it works when no chrono tasks are present

Fix an error where time travelling with no chrono tasks would cause a segmentation fault

---

.vscode/settings.json

Sets up the connection between SonarCloud and VSCode so that it can display warnings in the IDE

Connect vscode to SonarCloud

---

CMakeLists.txt
cmake/ClangTidy.cmake
cmake/CompilerOptions.cmake
cmake/Sanitizers.cmake

Partially replaces #68
#68 had extra intrusive options for valgrind which this leaves out.
#68 is left open in case we need those in the future

Add options for enabling sanitisers

---

src/PowerPlant.cpp
src/dsl/word/Buffer.hpp
src/extension/ChronoController.cpp
src/extension/IOController.hpp
src/extension/IOController_Posix.ipp
src/extension/IOController_Windows.ipp
src/extension/network/NUClearNetwork.cpp
src/extension/network/NUClearNetwork.hpp
src/threading/Reaction.hpp
src/threading/ReactionTask.cpp
src/threading/ReactionTask.hpp
src/threading/TaskScheduler.cpp
src/util/GroupDescriptor.hpp
src/util/ThreadPoolDescriptor.hpp
src/util/TypeMap.hpp

Use of atomics in the system has been improved.
Each of the atomic uses now has a memory order to help describe how the atomic is being used.
Also the get/set of the TypeMap was changed to atomics since most of the g++ versions that we target now support that

Improve the use of atomics

---

src/dsl/operation/TypeBind.hpp

Filtering for type bind was partially specialising the struct and rewriting the function. However it only really wanted to change one thing.
This instead uses a data struct to set for specific values

Simplify the filtering for TypeBind

---

src/dsl/operation/TypeBind.hpp

The loop prevention had the new ReactionEvent type that isn't in yet instead of ReactionStatistics which caused a loop

Fix up the incorrect type causing a stats loop

---

src/dsl/operation/TypeBind.hpp
src/id.hpp
src/message/ReactionStatistics.hpp
src/threading/ReactionTask.hpp
src/util/CallbackGenerator.hpp
src/util/usage_clock.cpp
src/util/usage_clock.hpp
tests/tests/api/ReactionStatistics.cpp
tests/tests/api/ReactionStatisticsTiming.cpp

Changes ReactionStatistics so it no longer only fires at the very end of a reaction. It will now fire progress updates as it goes through to allow monitoring of how reactions are going.
It also better conforms to trace file semantics so that they can be used to track reactions
Superceeds #99 as it integrates those changes too

Change how ReactionStatistics works to be more useful for monitoring events

---

.github/workflows/macos.yaml
.github/workflows/windows.yaml
src/PowerPlant.cpp
src/PowerPlant.hpp
src/dsl/word/UDP.hpp
src/extension/IOController.hpp
src/extension/IOController_Posix.ipp
src/extension/IOController_Windows.ipp
src/util/platform.hpp
tests/tests/dsl/UDP.cpp

Currently shutdowns aren't always reliable as when the Shutdown event is emitted, the scheduler itself hasn't been told to stop. Therefore the on<Always> that the IO Controller runs in may decide to start up again before the scheduler stops accepting tasks.
It will then sit on the poll forever

Make shutdowns more reliable by making poll have its own running flag

---

src/dsl/operation/ChronoTask.hpp
src/extension/IOController.hpp
src/threading/ReactionTask.hpp
src/threading/TaskScheduler.hpp
src/util/GroupDescriptor.hpp
tests/tests/util/serialise/serialise.cpp

Swaps to using hidden friends for operators.
They are superior as they allow conversions to apply to both sides of the comparision.
Also the comparision is only considered if one of the sides of the comparision is of the correct class type.

Swap to using hidden friends for operators

---

src/PowerPlant.cpp
src/PowerPlant.hpp
src/threading/TaskScheduler.cpp
src/threading/TaskScheduler.hpp
tests/test_util/TestBase.hpp
tests/tests/api/TimeTravel.cpp
tests/tests/api/TimeTravelFrozen.cpp
tests/tests/dsl/Every.cpp
tests/tests/dsl/Idle.cpp
tests/tests/dsl/IdleSync.cpp
tests/tests/dsl/TCP.cpp
tests/tests/dsl/Watchdog.cpp
tests/tests/dsl/emit/Delay.cpp

The current tests use on<Watchdog> for timing out tests.
This doesn't work if you manipulate the clock as the watchdog may never fire.
This changes it to just waiting for a specific amount of real time before ending the test.
Also makes the following other changes
- Makes the amount of time to wait a constuctor arugment rather than a template argument
- Makes a Fail struct that can be emitted to fail the test with a message (used by timeout)
- Adds a force option to powerplant shutdown to make it remove all queued tasks

Change test timeouts to be in realtime

---

src/Reactor.hpp
src/dsl/word/Trigger.hpp
src/dsl/word/With.hpp
tests/tests/dsl/DSLOrdering.cpp

Alllowing multiple values in Trigger and With
e.g.
```cpp
on<Trigger<A, B>>
```
It was never needed as you can have two trigger statements.
It also often lead to bugs where a misplaced `>` would make the Trigger take future DSL keywords.

Prevent multiple values in Trigger and With

---

src/dsl/fusion/BindFusion.hpp
src/dsl/fusion/FindWords.hpp
src/dsl/fusion/GetFusion.hpp
src/dsl/fusion/GroupFusion.hpp
src/dsl/fusion/PoolFusion.hpp
src/dsl/fusion/PostconditionFusion.hpp
src/dsl/fusion/PreconditionFusion.hpp
src/dsl/fusion/PriorityFusion.hpp
src/util/meta/Filter.hpp
tests/tests/dsl/GroupPool.cpp

All of the DSL fusions were using the exact same structure to filter their words down to those that had the functions they wanted.
This pulls that common logic out into a metafunction and uses it to simplify the code.

Bring the dsl word filtering into a common metaprogram

---

.github/workflows/gcc.yaml
.github/workflows/macos.yaml
.github/workflows/windows.yaml
src/extension/IOController.hpp
src/extension/IOController_Posix.ipp
src/extension/IOController_Windows.ipp
src/threading/scheduler/Pool.cpp
src/threading/scheduler/Pool.hpp
tests/tests/api/TimeTravelFrozen.cpp
tests/tests/dsl/Idle.cpp
tests/tests/dsl/IdleSingle.cpp
tests/tests/dsl/IdleSingleGlobal.cpp
tests/tests/dsl/IdleSync.cpp
tests/tests/dsl/Watchdog.cpp

Santizers (asan, tsan, ubsan, msan etc) found some issues in the code.
Some of them were technically impossible but having clean sanitizer output makes it easier to find problems in the future.

Address some issues found by the sanitizers

---

src/message/LogMessage.hpp
src/message/ReactionStatistics.hpp
src/threading/Reaction.cpp
src/threading/Reaction.hpp
src/threading/ReactionTask.cpp
src/threading/ReactionTask.hpp
src/threading/scheduler/Pool.hpp
src/threading/scheduler/Scheduler.cpp
tests/tests/log/Log.cpp

Some of the information required for good trace logs wasn't available or was wrong.
This fixes the code so that the correct information is available to make traces.
Future PRs which could improve the amount of information available for tracing are possible too.

Improve some of the statistics to allow for better tracing

---

src/PowerPlant.cpp
tests/tests/api/TimeTravel.cpp
tests/tests/api/TimeTravelFrozen.cpp
tests/tests/dsl/Every.cpp
tests/tests/dsl/IO.cpp
tests/tests/dsl/TCP.cpp
tests/tests/dsl/UDP.cpp
tests/tests/dsl/Watchdog.cpp
tests/tests/dsl/emit/Delay.cpp

This PR stops the installation of NUClear extensions by default.
They will need to instead be installed manually after powerplant creation.
In order for tracing to be effective, it needs to be installed early in the process.
Having these always installed extensions made it difficult to inject tracing at the right moment.
Additionally often these extensions weren't even needed and would still run, this way only the extensions that are required will be installed.

Stop installing extensions by default

---

src/dsl/word/MainThread.hpp
src/dsl/word/Pool.hpp
src/threading/scheduler/Pool.cpp
src/threading/scheduler/Pool.hpp
src/threading/scheduler/Scheduler.cpp
src/threading/scheduler/Scheduler.hpp
src/util/ThreadPoolDescriptor.hpp

Currently when the system shuts down it will stop any new tasks from being added to the thread pools.
For some tasks like tracing, we want to be able to see tasks and accept tasks even after all the other pools have finished so we can trace events like Shutdown and emits that happen during the shutdown process.
This adds a new flag to custom pools that let them ignore the first shutdown state, and instead wait until the other pools have shut down before they stop running.

Add a new thread pool option to allow the pool to live and accept tasks after shutdown

---

.github/workflows/sonarcloud.yaml
.github/workflows/windows.yaml
src/extension/ChronoController.cpp
src/util/precise_sleep.cpp
tests/test_util/TestBase.hpp
tests/tests/api/ReactionStatisticsTiming.cpp
tests/tests/api/TimeTravelFrozen.cpp
tests/tests/dsl/IdleCrossPool.cpp
tests/tests/dsl/IdleGlobal.cpp
tests/tests/dsl/IdleSingle.cpp
tests/tests/dsl/IdleSingleGlobal.cpp
tests/tests/dsl/IdleSync.cpp
tests/tests/dsl/Inline.cpp
tests/tests/dsl/Sync.cpp
tests/tests/dsl/SyncMulti.cpp

Occasionally in CI, the chrono controller would fail to stop and continue to run even after shutdown had happened.
Looking at the traces it seems that the shutdown from chrono controller stays running forever as well as chrono controller continuing to emit tasks.
The only way this could happen is if shutdown failed to acquire the mutex forever.
By setting running to false first outside of the mutex the main chrono thread should stop emitting tasks if it's looping.
If it's sleeping on the condition variable then locking the mutex then notifying should ensure it wakes up.
Also when windows ran tests, often they would time out.
This was because the timer that was used for sleeping would often vastly overestimate the amount of sleep time.
For example, the sleep for 1ms tests were often …

Improve the reliability of windows time based actions

---

docs/dsl.rst

Mostly pretty easy stuff. Opted for `rst` features instead of HTML as well.

Improve the DSL docs page

---

src/dsl/word/UDP.hpp
src/threading/ReactionTask.hpp
src/util/TypeMap.hpp

- The `noexcept` specifier on an std::function will not compile in c++17 or c++20
- In c++20 is_pod is deprecated
- In c++20 the separate functions for atomic shared pointers are deprecated

Fix some issues that occur when compiling with c++17 or c++20

---

src/message/ReactionStatistics.cpp
src/message/ReactionStatistics.hpp

The variables representing thread pools are called `pool` throughout the rest of the code, not `threadpool`

Rename threadpool to pool

---

src/util/TypeMap.hpp

You would think that you should use an atomic shared pointer rather than a mutex protected shared pointer.
That would make sense, then you would potentially have a lock free implementation!
However the implementation as seen in libc++ and libstdc++ is to use a mutex protected shared pointer anyway.
But worse than that, it just uses a hashmap of mutexes to protect the shared pointers.
Specifically it looks like they just have 0xF mutexes and they hash the pointer addresses to pick one.
Having only a few mutexes for the entire map is a terrible idea and causes a lot of contention.
This is strictly worse than the already separated mutex per type that is achieved by this implementation.

Swap back to using mutexes to protect the type map

---

src/extension/TraceController.cpp

The trigger that starts the trace itself wasn't logged properly. This made it difficult to get a "zero time" for the trace.
Logging the BeginTrace reaction itself means you get to see when the begin trace was requested

Store trace events that mark the start of the trace

---

src/PowerPlant.cpp
src/PowerPlant.hpp
src/Reactor.hpp
src/message/LogMessage.hpp
src/util/Logger.cpp
src/util/Logger.hpp
src/util/string_join.hpp
tests/tests/util/string_join.cpp

This pulls the logging code out into its own class as it was getting more complex.
It also allows limiting sending of logs from a reactor. Sending out every trace message was causing a lot of overhead.
Now there are two variables in each reactor, one to describe the displayed log level `log_level` and one to describe the minimum emitted log level `min_log_level`

Refactor logging and allow setting a minimum log level that should not be emitted

---

src/LogLevel.hpp
src/PowerPlant.hpp
src/Reactor.cpp
src/Reactor.hpp
src/util/Logger.hpp
tests/tests/api/LogLevel.cpp
tests/tests/log/Log.cpp

Makes LogLevel into a smart enum. It can be used as an enum still for most cases, but makes the log API simplier, and also allows setting log levels from strings instead of just enum constants which makes it easier to configure

Make LogLevel a smart enum

---

.github/workflows/sonarcloud.yaml
CMakeLists.txt
src/CMakeLists.txt
tests/CMakeLists.txt

The coverage was calculated for the catch2 library since it's coming in as a FetchContent module. This changes how the coverage flags are applied so that only the NUClear library and the tests have coverage arcs on them.

Fix Sonarcloud Coverage by not including Catch2

---

src/clock.cpp
src/clock.hpp
src/dsl/operation/TypeBind.hpp
src/dsl/word/Always.hpp
src/dsl/word/Every.hpp
src/dsl/word/IO.hpp
src/dsl/word/Idle.hpp
src/dsl/word/Network.hpp
src/dsl/word/TCP.hpp
src/dsl/word/UDP.hpp
src/dsl/word/Watchdog.hpp
src/extension/ChronoController.cpp
src/extension/NetworkController.cpp
src/extension/network/NUClearNetwork.cpp
src/threading/Reaction.cpp
src/util/Logger.hpp
src/util/get_hostname.cpp
src/util/serialise/xxhash.cpp
src/util/serialise/xxhash.hpp
src/util/string_join.hpp

Addresses some minor points raised by sonarqube, also disabled some of the rules so this should trigger less issues

Address some issues found by sonarqube

---

src/PowerPlant.hpp
src/Reactor.hpp
src/dsl/word/emit/Watchdog.hpp
src/util/FunctionFusion.hpp
src/util/Sequence.hpp
tests/tests/util/FunctionFusion.cpp
tests/tests/util/moving.cpp

Function fusion technically runs std::forward on the same arguments multiple times, in theory this could mean that the second time a function gets those arguments they could have been moved away.
This one was interesting as I realised that I wasn't even forwarding the arguments all the way down. At the last level they were left as lvalue. After fixing this issue the actual bug could be fixed so that shared arguments will always be passed through as lvalues, while unique variables will only ever be sent to a single function and thus, forwarding them multiple times is fine as only one function will ever "see" the final value.

Fix the double forwarding bug in function fusion

---

src/dsl/store/ThreadStore.hpp
src/dsl/word/TaskScope.hpp
src/threading/ReactionTask.cpp
src/threading/ReactionTask.hpp
src/threading/scheduler/Pool.cpp
src/threading/scheduler/Pool.hpp

I would much prefer just to use the standard thread_local keyword for thread local storage rather than having custom properties. See which compilers are ok with this and if it's not too onerous change the minimum requirements for NUClear to match

Swap to just using thread_local for thread local storage

---

tests/test_util/executable_path.cpp

on osx, the executable path was using the size variable, however this wasn't holding the number of bytes put in the buffer, it instead just is used to output the required size if there was not enough. As a result, the string had nulls in it. Later when it was concatenated with an extension for traces, the nulls meant that the final path was just the binary name which was overwritten.
since PATH_MAX is used as the buffer size, we don't need to look at the space required as it should be PATH_MAX or less by definition.

Correct the executable path for osx

---

src/Reactor.hpp

Even with the min_log_level being gated not to include trace by default, it still slows down some code unexpectedly. Make it so that the feature has to be explicitly used rather than always being set to debug or above.

Make the min_log_level feature opt in

---

src/clock.hpp

The default clock for NUClear was supposed to be system_clock but was accidentally changed to steady_clock in #165

Change the default NUClear clock to system_clock

---

src/threading/Reaction.hpp
src/threading/scheduler/Scheduler.cpp

Currently every single task that is added to the scheduler is required to lock a pool mutex to find it's pool. There are too many mutex locks on this path currently and it's obviously slowing down the system as a whole.
While lock free queues will hopefully eventually solve the lower level queue problems, this higher level mutex to select a pool can be avoided by caching it on the reaction as once a reaction is created it will always target the same pool.

Cache pool information on reactions to avoid finding it each time

---

src/dsl/word/TCP.hpp
src/dsl/word/UDP.hpp
src/util/network/sock_t.hpp
tests/tests/dsl/UDP.cpp

getnameinfo is much better at converting socket addresses to strings, it can resolve hostnames etc as well.
Swap to using it for `sockt_t.address()` and just pass the sock_t objects through to consumers so they can decide how to work with them.

Swap to using getnameinfo for address names

---

src/dsl/word/Network.hpp
src/extension/NetworkController.cpp

Swap the thread local store to use const pointers instead of non const since the deserialisation does not need non const anyway

Swap to using const data for NetworkController
